const router = require("express").Router();
const PDFDocument = require("pdfkit");
const jwt = require("jsonwebtoken");
const User = require("../models/user");

// Helper: build resume PDF from data and pipe to res
function buildResumePdf(res, { name = '', cgpa = '', skills = [], projects = [] }) {
  const doc = new PDFDocument({ margin: 50 });

  res.setHeader("Content-Type", "application/pdf");
  res.setHeader("Content-Disposition", `attachment; filename="${(name || 'resume').replace(/\s+/g,'_')}.pdf"`);

  doc.pipe(res);

  // Header
  doc.fontSize(22).font('Helvetica-Bold').text(name || 'Unnamed', { align: 'center' });
  doc.moveDown(0.25);
  doc.fontSize(10).font('Helvetica').fillColor('gray').text(`CGPA: ${cgpa || 'N/A'}`, { align: 'center' });
  doc.moveDown(1);

  // Divider
  doc.moveTo(50, doc.y).lineTo(doc.page.width - 50, doc.y).strokeColor('#aaaaaa').stroke();
  doc.moveDown(1);

  // Skills
  doc.fontSize(14).fillColor('black').font('Helvetica-Bold').text('Skills');
  doc.moveDown(0.25);
  doc.fontSize(11).font('Helvetica');
  if (Array.isArray(skills) && skills.length) {
    doc.text(skills.join(', '));
  } else {
    doc.text('N/A');
  }
  doc.moveDown(0.75);

  // Projects
  doc.fontSize(14).font('Helvetica-Bold').text('Projects');
  doc.moveDown(0.25);
  doc.fontSize(11).font('Helvetica');
  if (Array.isArray(projects) && projects.length) {
    projects.forEach((p, i) => {
      doc.text(`${i + 1}. ${p}`);
      doc.moveDown(0.25);
    });
  } else {
    doc.text('N/A');
  }

  // Footer
  doc.moveDown(1);
  doc.fontSize(9).fillColor('gray').text('Generated by PlacementPro', { align: 'center' });

  doc.end();
}

// Improved resume layout: supports DB-backed user if Authorization Bearer token provided
router.post("/generateResume", async (req, res) => {
  try {
    let data = null;

    // If Authorization header present and JWT secret configured, try to load user from DB
    const auth = req.headers.authorization || req.headers.Authorization;
    if (auth && auth.startsWith('Bearer ') && process.env.JWT_SECRET) {
      const token = auth.split(' ')[1];
      try {
        const payload = jwt.verify(token, process.env.JWT_SECRET);
        if (payload && payload.id) {
          // Only attempt DB lookup if mongoose is connected
          if (typeof User.findById === 'function') {
            const user = await User.findById(payload.id).lean();
            if (user) {
              data = {
                name: user.name,
                cgpa: user.cgpa,
                skills: user.skills || [],
                projects: user.projects || []
              };
            }
          }
        }
      } catch (e) {
        // invalid token — continue to fallback to request body
        console.warn('Invalid JWT for resume generation:', e.message);
      }
    }

    // Fallback to request body if no DB user found
    if (!data) {
      const { name = '', cgpa = '', skills = [], projects = [] } = req.body || {};
      data = { name, cgpa, skills, projects };
    }

    buildResumePdf(res, data);
  } catch (err) {
    console.error('Error generating resume:', err);
    res.status(500).json({ error: 'Failed to generate resume' });
  }
});

// Dev-only: seed a test user (only when NODE_ENV !== 'production')
router.post('/dev/seedUser', async (req, res) => {
  if (process.env.NODE_ENV === 'production') return res.status(403).json({ error: 'Forbidden' });
  if (!process.env.MONGO_URI) return res.status(400).json({ error: 'Mongo not configured' });
  try {
    const bcrypt = require('bcryptjs');
    const UserModel = require('../models/user');
    const existing = await UserModel.findOne({ email: 'dileep@gmail.com' });
    if (existing) return res.json({ message: 'User already exists', user: { email: existing.email } });
    const hashed = await bcrypt.hash('123456', 10);
    const user = await UserModel.create({ name: 'Dileep', email: 'dileep@gmail.com', password: hashed, role: 'student', cgpa: 8.5, skills: ['JS','Node'], projects: ['A','B'] });
    return res.json({ message: 'Seeded', user: { id: user._id, email: user.email } });
  } catch (err) {
    console.error('Seed error', err);
    res.status(500).json({ error: 'Seed failed' });
  }
});

module.exports = router;